### ISSUE TITLE
Change the "Are you faster than light? Sure?" header to show the best player's name instead of light

### ISSUE THREAD

**Issue by lachatak** [lachatak/raspberrypi-reaction-test#22]
if it is empty fall back to "light"
possibly highlight the name with a green bold italic caracters

**Comment by lachatak** [comment]
- make paragraphs more readable
- put the two logo next to each other as in ipad the form is not visible (or find some better way to show both of the pictures)

**Comment by tamaspolgar** [comment]
if you put the two pictures next to each other, they will be too small.
why do you need this other picture in? this is not intended to be an advert site.

**Comment by lachatak** [comment]
it is pushed now
you can win a now tv set-top-box. that is why..
i like how it is now BTW but if you have better idea..

**Comment by lachatak** [comment]
done
